---
title: "03_worried_boot"
author: "Stróbl Anita"
date: "Last compiled on `r format(Sys.time(), '%d/%m/%Y, %X %Z')`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: hide
editor_options: 
  markdown: 
    wrap: 72
---

```{r message=FALSE, warning=FALSE}

options(scipen = 999)

library(psych)
library(tidyverse)
library(dplyr)
library(lme4)
library(lmerTest)
library(lmeresampler)
library(MuMIn)
library(broom)
library(lavaan)
library(sjPlot)
library(car)
library(data.table)
library(tibble)
library(lubridate)
library(naniar)
library(hms)
library(skimr)
library(ggplot2)
library(janitor)
library(scales) 
library(FSA)
library(PMCMRplus)
library(lsr)
library(misty)
library(rstatix)
library(see)
library(gridExtra)
library(see)
library(gridExtra)
library(semTools)
library(performance)
library(metafor)
library(readr)
library(flextable)

```

``` {r import dataset, message=FALSE, warning=FALSE}

dat_1 <- read_csv("dat_1_m.csv")

```

``` {r read lmer models}

m_n <- readRDS("lmer_models/m_n.rds")
m_p <- readRDS("lmer_models/m_p.rds")
m_d <- readRDS("lmer_models/m_d.rds")
m_np <- readRDS("lmer_models/m_np.rds")
m_pd <- readRDS("lmer_models/m_pd.rds")
m_nd <- readRDS("lmer_models/m_nd.rds")
m_all <- readRDS("lmer_models/m_all.rds")

```

``` {r bootstrap}

# lmeresampler package

boot_m_n <- bootstrap(m_n, .f = function(x) {
            r2 <- MuMIn::r.squaredGLMM(x)
            c(fixef(x), R2m = r2[1, "R2m"], R2c = r2[1, "R2c"])}, 
            type = "wild", 
            hccme =  "hc2", aux.dist = "mammen", 
            B = 1000, resample = c(TRUE, TRUE))

boot_m_p <- bootstrap(m_p, .f = function(x) {
            r2 <- MuMIn::r.squaredGLMM(x)
            c(fixef(x), R2m = r2[1, "R2m"], R2c = r2[1, "R2c"])}, 
            type = "wild", 
            hccme =  "hc2", aux.dist = "mammen", 
            B = 1000, resample = c(TRUE, TRUE))

boot_m_d <- bootstrap(m_d, .f = function(x) {
            r2 <- MuMIn::r.squaredGLMM(x)
            c(fixef(x), R2m = r2[1, "R2m"], R2c = r2[1, "R2c"])}, 
            type = "wild", 
            hccme =  "hc2", aux.dist = "mammen", 
            B = 1000, resample = c(TRUE, TRUE))

boot_m_np <- bootstrap(m_np, .f = function(x) {
             r2 <- MuMIn::r.squaredGLMM(x)
             c(fixef(x), R2m = r2[1, "R2m"], R2c = r2[1, "R2c"])}, 
             type = "wild", 
             hccme =  "hc2", aux.dist = "mammen", 
             B = 1000, resample = c(TRUE, TRUE))

boot_m_pd <- bootstrap(m_pd, .f = function(x) {
             r2 <- MuMIn::r.squaredGLMM(x)
             c(fixef(x), R2m = r2[1, "R2m"], R2c = r2[1, "R2c"])}, 
             type = "wild", 
             hccme =  "hc2", aux.dist = "mammen", 
             B = 1000, resample = c(TRUE, TRUE))

boot_m_nd <- bootstrap(m_nd, .f = function(x) {
             r2 <- MuMIn::r.squaredGLMM(x)
             c(fixef(x), R2m = r2[1, "R2m"], R2c = r2[1, "R2c"])}, 
             type = "wild", 
             hccme =  "hc2", aux.dist = "mammen", 
             B = 1000, resample = c(TRUE, TRUE))

boot_m_all <- bootstrap(m_all, .f = function(x) {
              r2 <- MuMIn::r.squaredGLMM(x)
              c(fixef(x), R2m = r2[1, "R2m"], R2c = r2[1, "R2c"])}, 
              type = "wild", 
              hccme =  "hc2", aux.dist = "mammen", 
              B = 1000, resample = c(TRUE, TRUE))


```

``` {r save read boot rds}

# saveRDS(boot_m_n, "boot_models/boot_m_n.rds")
# saveRDS(boot_m_p, "boot_models/boot_m_p.rds")
# saveRDS(boot_m_d, "boot_models/boot_m_d.rds")
# saveRDS(boot_m_np, "boot_models/boot_m_np.rds")
# saveRDS(boot_m_pd, "boot_models/boot_m_pd.rds")
# saveRDS(boot_m_nd, "boot_models/boot_m_nd.rds")
# saveRDS(boot_m_all, "boot_models/boot_m_all.rds")

# boot_m_n <- readRDS("boot_models/boot_m_n.rds")
# boot_m_p <- readRDS("boot_models/boot_m_p.rds")
# boot_m_d <- readRDS("boot_models/boot_m_d.rds")
# boot_m_np <- readRDS("boot_models/boot_m_np.rds")
# boot_m_pd <- readRDS("boot_models/boot_m_pd.rds")
# boot_m_nd <- readRDS("boot_models/boot_m_nd.rds")
# boot_m_all <- readRDS("boot_models/boot_m_all.rds")

```

``` {r save read boot r2 rds}

# saveRDS(boot_m_n, "boot_models/boot_m_n_r2.rds")
# saveRDS(boot_m_p, "boot_models/boot_m_p_r2.rds")
# saveRDS(boot_m_d, "boot_models/boot_m_d_r2.rds")
# saveRDS(boot_m_np, "boot_models/boot_m_np_r2.rds")
# saveRDS(boot_m_pd, "boot_models/boot_m_pd_r2.rds")
# saveRDS(boot_m_nd, "boot_models/boot_m_nd_r2.rds")
# saveRDS(boot_m_all, "boot_models/boot_m_all_r2.rds")

boot_m_n_r2 <- readRDS("boot_models/boot_m_n_r2.rds")
boot_m_p_r2 <- readRDS("boot_models/boot_m_p_r2.rds")
boot_m_d_r2 <- readRDS("boot_models/boot_m_d_r2.rds")
boot_m_np_r2 <- readRDS("boot_models/boot_m_np_r2.rds")
boot_m_pd_r2 <- readRDS("boot_models/boot_m_pd_r2.rds")
boot_m_nd_r2 <- readRDS("boot_models/boot_m_nd_r2.rds")
boot_m_all_r2 <- readRDS("boot_models/boot_m_all_r2.rds")

```

``` {r boot table}

# lmersampler package

boot_list <- list(
  "Negatív" = boot_m_n_r2,
  "Pozitív" = boot_m_p_r2,
  "Dezorganizált" = boot_m_d_r2,
  "Negatív - Pozitív" = boot_m_np_r2,
  "Pozitív - Dezorganizált" = boot_m_pd_r2,
  "Negatív - Dezorganizált" = boot_m_nd_r2,
  "Pozitív - Negatív - Dezorganizált" = boot_m_all_r2)

boot_table_f <- function(boot_table) {
  median <- apply(boot_table$replicates, 2, median) 
  se <- apply(boot_table$replicates, 2, sd) 
  ci <- confint(boot_table, type = "perc")
  p_vals <- apply(boot_table$replicates, 2, function(x) { 
    2 * min(mean(x <= 0, na.rm = TRUE), mean(x >= 0, na.rm = TRUE))
  })
  results <- data.frame(
    term          = ci$term,
    orig_estimate = ci$estimate,
    boot_median   = median,
    boot_se       = se,
    boot_ci_lower = ci$lower,
    boot_ci_upper = ci$upper,
    boot_p_value  = p_vals,
    stringsAsFactors = FALSE
)
  return(results)
}

all_results <- map_df(boot_list, boot_table_f, .id = "model")

boot_lmer_table <- all_results %>%
  filter(!term %in% c("(Intercept)", "R2m.R2m", "R2c.R2c")) %>%
  mutate(term = factor(term,
                      levels = c("sch_neg", "sch_pos", "sch_dis"),
                      labels = c("Negatív", "Pozitív", "Dezorganizált")))

saveRDS(boot_lmer_table, "boot_models/boot_lmer_table.rds")

boot_lmer_r2_table <- all_results %>%
  filter(term %in% c("R2m.R2m", "R2c.R2c")) %>%
  mutate(term = factor(term,
                      levels = c("R2m.R2m", "R2c.R2c"),
                      labels = c("Marginal R2", "Conditional R2")))

saveRDS(boot_lmer_r2_table, "boot_models/boot_lmer_r2_table.rds")

```

``` {r save tables in docs}

# Boot table

boot_lmer_form<- boot_lmer_table %>%
  mutate(
    boot_p_value = format(round(boot_p_value, 3), nsmall = 3, decimal.mark = ","),
    across(where(is.numeric), ~ format(round(.x, 2), nsmall = 2, decimal.mark = ",")))

write_csv(boot_lmer_form, "boot_models/boot_lmer_form.csv")
boot_lmer_form_csv <- read_csv("boot_models/boot_lmer_form.csv")

boot_lmer_docx <- flextable(boot_lmer_form_csv)
boot_lmer_docx <- autofit(boot_lmer_docx)
save_as_docx(boot_lmer_docx, path = "tables/boot_lmer.docx")

# Boot r2 table
boot_r2_form <- boot_lmer_r2_table %>%
  mutate(
    boot_p_value = format(round(boot_p_value, 3), nsmall = 3, decimal.mark = ","),
    orig_estimate	= format(round(orig_estimate, 3), nsmall = 3, decimal.mark = ","),
    boot_median = format(round(boot_median, 3), nsmall = 3, decimal.mark = ","),
    across(where(is.numeric), ~ format(round(.x, 2), nsmall = 2, decimal.mark = ",")))

write_csv(boot_r2_form, "boot_models/boot_r2_form.csv")
boot_lmer_r2_form_csv <- read_csv("boot_models/boot_r2_form.csv")

boot_lmer_r2_docx <- flextable(boot_lmer_r2_form_csv)
boot_lmer_r2_docx <- autofit(boot_lmer_r2_docx)
save_as_docx(boot_lmer_r2_docx, path = "tables/boot_lmer_r2.docx")

```

``` {r boot vis}

boot_lmer_table$term <- factor(boot_lmer_table$term, 
                               levels = c("Pozitív", "Negatív", "Dezorganizált"))
boot_lmer_table$model <- factor(boot_lmer_table$model, 
                                levels = c("Pozitív - Negatív - Dezorganizált",
                                           "Negatív - Dezorganizált",
                                           "Pozitív - Dezorganizált",
                                           "Negatív - Pozitív",
                                           "Dezorganizált",
                                           "Pozitív",
                                           "Negatív"))

boot_lmer_table <- boot_lmer_table %>%
  mutate(p_sign = case_when(
    boot_p_value < 0.05 ~ "p < 0,05",
    boot_p_value > 0.05 ~ "p > 0,05"))


colors <- c("Pozitív" = "#FC8D62FF",
            "Negatív" = "#80B1D3", 
            "Dezorganizált" = "#BC80BD")
shapes <- c("p < 0,05"= 16,
           "p > 0,05" = 1)

boot_worried <- 
  ggplot(boot_lmer_table, aes(x = (boot_ci_lower + boot_ci_upper) / 2, y = model, xmin = boot_ci_lower, xmax = boot_ci_upper)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "darkgrey", linewidth = 0.5, alpha = 0.8) +
  geom_pointrange(
    aes(color = term, shape = p_sign, group = term), 
    position = position_dodge(width = 0.3), 
    linewidth = 0.8, size = 0.8) +
  scale_color_manual(name = "Dimenzió",
                     labels = c("Pozitív", "Negatív", "Dezorganizált"),
                     values = colors) +
  scale_shape_manual(name = "Szignifikancia",
                     labels = c("p < 0,05", "p > 0,05"),
                     values = shapes) +
  labs(title = "Aggodalom - multilevel modellek bootstrappelt becslései",
       x = "Bootstrappelt becslések (95% CI)", 
       y = NULL) + 
  theme_minimal(base_size = 10) +
  theme(
    legend.position = "right",
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank())

print(boot_worried)

ggsave("plots/boot_worried.png", plot = boot_worried, height = 12, width = 20, units = "cm", dpi = 300)

```

