---
title: "BA szakdolgozat"
author: "Stróbl Anita"
date: "Last compiled on `r format(Sys.time(), '%d/%m/%Y, %X %Z')`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: hide
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}

options(scipen = 999)

library(psych)
library(tidyverse)
library(dplyr)
library(lme4)
library(lmerTest)
library(broom)
library(lavaan)
library(sjPlot)
library(car)
library(data.table)
library(tibble)
library(lubridate)
library(naniar)
library(hms)
library(skimr)
library(ggplot2)
library(janitor)
library(scales) 
library(FSA)
library(PMCMRplus)
library(lsr)
library(misty)
library(rstatix)
library(see)
library(gridExtra)

```

``` {r import_dataset}

dat_1 <- read.csv("dat_1.csv")

```

``` {r sex_edu_factor}

# Making sex variable considered as a factor
dat_1  <-  
  dat_1 %>%
  mutate(sex = factor(sex, levels = c(1, 2, 3), labels = c("Female", "Male", "Other")))

# Making edu variable consideres as a factor
dat_1  <-  dat_1 %>%
  mutate(edu = factor(edu, levels = c(1, 2, 3, 4, 5, 6, 7), 
                      labels = c("Általános iskola vagy alacsonyabb (1)",
                                 "Középiskola érettségi nélkül (2)", 
                                 "Középiskola érettségivel (3)",
                                 "Egyetemi alap diploma (4)",
                                 "Egyetemi mester diploma (5)",
                                 "Doktori fokozat (PhD) (6)", 
                                 "Egyéb (7)")))

```

``` {r MSS_sum}

mssb_items <- list(
  mssb_reverse = c("mss_bh_4", "mss_bh_10", "mss_bh_25", "mss_bh_37"),
  mssb_neg = paste0("mss_bh_", seq(1, 37, by = 3)),
  mssb_pos = paste0("mss_bh_", seq(2, 38, by = 3)),
  mssb_dis = paste0("mss_bh_", seq(3, 36, by = 3))     )

dat_1 <- dat_1 %>% 
  mutate(dat = "dat_1") %>%
  mutate(sch_neg = rowSums(select(., all_of(mssb_items$mssb_neg)), na.rm = T),
        sch_pos = rowSums(select(., all_of(mssb_items$mssb_pos)), na.rm = T),
        sch_dis = rowSums(select(., all_of(mssb_items$mssb_dis)), na.rm = T))

```

``` {r demography}

# Creating distinct data
dat_distinct <- dat_1 %>%
  distinct(id_esm, .keep_all = TRUE)

dat_distinct_dem <- dat_distinct %>%
  select(id_esm, age, sex, edu)

# Creating demography tibble
summary_dem <- dat_distinct_dem %>% 
  summarize(n = n(), 
            age_mean = round(mean(age), digits = 2), 
            age_sd = round(sd(age), digits = 2), 
            age_mdn = round(median(age), digits = 2), 
            age_min = round(min(age), digits = 2),  
            age_max = round(max(age), digits = 2), 
            n_female = round(sum(sex == "Female", na.rm = T), digits = 2), 
            female_pct = round(100/n*sum(sex == "Female", na.rm = T), digits = 2), 
            n_male = round(sum(sex == "Male", na.rm = T), digits = 2), 
            male_pct = round(100/n*sum(sex == "Male", na.rm = T), digits = 2), 
            n_other = round(sum(sex == "Other", na.rm = T), digits = 2), 
            edu_1_pct = round((sum(edu == "Általános iskola vagy alacsonyabb (1)", na.rm=T)/n())*100, digits = 2), 
            n_edu_1 = round((sum(edu == "Általános iskola vagy alacsonyabb (1)", na.rm=T)), digits = 2), 
            edu_2_pct = round((sum(edu == "Középiskola érettségi nélkül (2)",na.rm=T)/n())*100, digits = 2), 
            n_edu_2 = round((sum(edu == "Középiskola érettségi nélkül (2)",na.rm=T)), digits = 2), 
            edu_3_pct = round((sum(edu == "Középiskola érettségivel (3)", na.rm=T)/n())*100, digits = 2), 
            n_edu_3 = round((sum(edu == "Középiskola érettségivel (3)", na.rm=T)), digits = 2), 
            edu_4_pct = round((sum(edu == "Egyetemi alap diploma (4)", na.rm=T)/n())*100, digits = 2), 
            n_edu_4 = round((sum(edu == "Egyetemi alap diploma (4)", na.rm=T)), digits = 2), 
            edu_5_pct = round((sum(edu == "Egyetemi mester diploma (5)", na.rm=T)/n())*100, digits = 2), 
            n_edu_5 = round((sum(edu == "Egyetemi mester diploma (5)", na.rm=T)), digits = 2), 
            edu_6_pct = round((sum(edu == "Doktori fokozat (PhD) (6)", na.rm=T)/n())*100, digits = 2), 
            n_edu_6 = round((sum(edu == "Doktori fokozat (PhD) (6)", na.rm=T)), digits = 2), 
            edu_7_pct = round((sum(edu == "Egyéb (7)", na.rm=T)/n())*100, digits = 2), 
            n_edu_7 = round((sum(edu == "Egyéb (7)", na.rm=T)), digits = 2))

tibble(summary_dem)

```

``` {r complience}

# Creating distinct data
dat_distinct <- dat_1 %>%
  distinct(id_esm, .keep_all = TRUE)

# Identifying day of quitting
dat_maxday <- dat_1 %>%
  select(id_esm, day, worried) %>%
  filter(!is.na(worried)) %>%
  group_by(id_esm) %>%
  summarise(maxday = max(day))

dat_1 <- dat_1 %>%
  select(-any_of("maxday")) %>%
  left_join(dat_maxday, by = "id_esm")

# Number of days spent in the study
dat_spentday <- dat_1 %>%
  select(id_esm, maxday) %>%
  distinct() %>%
  reframe(N = n(),
          mean_days = round(mean(maxday, na.rm = T), digits = 2),
          mdn_days = round(median(maxday, na.rm = T), digits = 2), 
          sd_days = round(sd(maxday, na.rm = T), digits = 2), 
          min_days = round(min(maxday, na.rm = T), digits = 2), 
          max_days = round(max(maxday, na.rm = T), digits = 2))

tibble(dat_spentday)

# Calculating complience rate (percentage)
dat_compl <- dat_1 %>%
  select(id_esm, day, beep, maxday, worried) %>%
  distinct() %>%
  group_by(id_esm) %>%
  reframe(compl_n  = sum(!is.na(worried)),
          all_answer = maxday * 8,
          compl_pct = (compl_n / all_answer) * 100) %>%
  ungroup() %>%
  reframe(N = n(),
          mean_compl = round(mean(compl_pct, na.rm = T), digits = 2),
          mdn_compl = round(median(compl_pct, na.rm = T), digits = 2),
          sd_compl = round(sd(compl_pct, na.rm = T), digits = 2),
          min_compl = round(min(compl_pct, na.rm = T), digits = 2),
          max_compl = round(max(compl_pct, na.rm = T), digits = 2))
  
tibble(dat_compl)

# calculating number of surveys completed
dat_compl_n <- dat_1 %>%
  select(id_esm, day, beep, maxday, worried) %>%
  distinct() %>%
  group_by(id_esm) %>%
  reframe(compl_n  = sum(!is.na(worried)),
          all_answer = maxday * 8,
          compl_pct = (compl_n / all_answer) * 100) %>%
  ungroup() %>%
  reframe(N = n(),
          mean_compl = round(mean(compl_n, na.rm = T), digits = 2),
          mdn_compl = round(median(compl_n, na.rm = T), digits = 2),
          sd_compl = round(sd(compl_n, na.rm = T), digits = 2),
          min_compl = round(min(compl_n, na.rm = T), digits = 2),
          max_compl = round(max(compl_n, na.rm = T), digits = 2))
  
tibble(dat_compl_n)

``` 

``` {r complience_visualization}

dat_compl_vis <- dat_1 %>%
  select(id_esm, day, beep, maxday, worried) %>%
  distinct() %>%
  group_by(id_esm) %>%
  reframe(compl_n  = sum(!is.na(worried)),
          all_answer = maxday * 8,
          compl_pct = (compl_n / all_answer) * 100) %>%
  ungroup() %>%
  distinct()
  
compl_vis <- ggplot(dat_compl_vis) +
  geom_histogram(aes(compl_pct), bins = 40, fill = "#8DD3C7") +
  labs(
    x = "Együttműködési ráta (%)",
    y = "Résztvevők száma") +
  theme_minimal(base_size = 12) +
  theme(axis.title = element_text(size = 10))

```

``` {r MSS_descriptive}

# Creating distinct data
dat_distinct <- dat_1 %>%
  distinct(id_esm, .keep_all = TRUE)

dat_distinct_mss <- dat_distinct %>%
  select(id_esm, sch_neg, sch_pos, sch_dis)

# # Creating MSS descriptive table
summary_mss <- dat_distinct_mss %>% 
  summarize(mean_sch_pos = round(mean(sch_pos, na.rm=T), digits = 2), 
            sd_sch_pos = round(sd(sch_pos, na.rm=T), digits = 2),  
            mdn_sch_pos = round(median(sch_pos, na.rm=T), digits = 2), 
            max_sch_pos = round(max(sch_pos, na.rm=T), digits = 2), 
            min_sch_pos = round(min(sch_pos, na.rm=T), digits = 2), 
            mean_sch_neg = round(mean(sch_neg, na.rm=T), digits = 2), 
            sd_sch_neg = round(sd(sch_neg, na.rm=T), digits = 2), 
            mdn_sch_neg = round(median(sch_neg, na.rm=T), digits = 2), 
            max_sch_neg = round(max(sch_neg, na.rm=T), digits = 2), 
            min_sch_neg = round(min(sch_neg, na.rm=T), digits = 2), 
            mean_sch_dis = round(mean(sch_dis, na.rm=T), digits = 2), 
            sd_sch_dis = round(sd(sch_dis, na.rm=T), digits = 2), 
            mdn_sch_dis = round(median(sch_dis, na.rm=T), digits = 2),
            max_sch_dis = round(max(sch_dis, na.rm=T), digits = 2), 
            min_sch_dis = round(min(sch_dis, na.rm=T), digits = 2))

tibble(summary_mss)

```

``` {r MSS_visualization}

dat_mss_vis <- dat_1 %>%
  select(id_esm, sch_neg, sch_pos, sch_dis) %>%
  distinct() %>%
  pivot_longer(cols = c(sch_neg, sch_pos, sch_dis), names_to = "group", values_to = "value") %>%
  mutate(group = factor(group, 
                        levels = c("sch_pos", "sch_neg", "sch_dis",
                        labels = c("Pozitív", "Negatív", "Dezorganizált"))))

sch_color <- c("#FC8D62", "#80B1D3", "#BC80BD")

mss_vis <- ggplot(dat_mss_vis, aes(group, value, fill = group)) +
  geom_violinhalf(color = NA, alpha = 0.9, position = position_nudge(x = 0.2, y = 0)) +
  geom_boxplot(color = "#505354", alpha = 0.9, width = 0.25, position = position_dodge(width = 0.3), outlier.shape = NA) + 
  scale_fill_manual(name = "MSS-B dimenziók", 
                    labels = c("Pozitív", "Negatív", "Dezorganizált"), values = sch_color) +
  scale_x_discrete(labels =c("Pozitív", "Negatív", "Dezorganizált"))  +
  labs(x = "MSS-B dimenziók", 
       y = "MSS-B dimenziók pontszáma") + 
  theme_minimal(base_size = 12) +
  theme(axis.title = element_text(size = 10), 
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.position = "right")

print(mss_vis)

```

``` {r MSS_reliability}

mssb_items <- list(
  mssb_reverse = c("mss_bh_4", "mss_bh_10", "mss_bh_25", "mss_bh_37"),
  mssb_neg = paste0("mss_bh_", seq(1, 37, by = 3)),
  mssb_pos = paste0("mss_bh_", seq(2, 38, by = 3)),
  mssb_dis = paste0("mss_bh_", seq(3, 36, by = 3)))

dat_distinct <- dat_1 %>%
  distinct(id_esm, .keep_all = TRUE)

items_pos <- dat_distinct %>%
  select(all_of(mssb_items$mssb_pos))
cat("\n--- Pozitív reliabilitás ---\n")
alpha_pos <- psych::alpha(items_pos, check.keys = T)
item.alpha(items_pos)
print(alpha_pos)

items_neg <- dat_distinct %>%
  select(all_of(mssb_items$mssb_neg))
cat("\n--- Negatív reliabilitás ---\n")
alpha_neg <- psych::alpha(items_neg, check.keys = T)
item.alpha(items_neg)
print(alpha_neg)

items_dis <- dat_distinct %>%
  select(all_of(mssb_items$mssb_dis))
cat("\n--- Dezorganizált reliabilitás ---\n")
alpha_dis <- psych::alpha(items_dis, check.keys = T)
item.alpha(items_dis)
print(alpha_dis)

# Ha item(ek) reliabilitása kifejezetten alacsony, akkor érdemes kizárni őket a modellből?
# pl. mss_bh_38 a = 0.13(?)
```

``` {r MSS_pos_reliability_if_items_dropped}

# items dropped: mss_bh_2 (pos), mss_bh_38 (pos)

mssb_items_dropped <- list(
  mssb_reverse = c("mss_bh_4", "mss_bh_10", "mss_bh_25", "mss_bh_37"),
  mssb_neg = paste0("mss_bh_", seq(1, 37, by = 3)),
  mssb_pos = c("mss_bh_5", "mss_bh_8", "mss_bh_11", "mss_bh_14", "mss_bh_17", "mss_bh_20", "mss_bh_23", "mss_bh_26", "mss_bh_29", "mss_bh_32", "mss_bh_35"),
  mssb_dis = paste0("mss_bh_", seq(3, 36, by = 3)))

dat_distinct <- dat_1 %>%
  distinct(id_esm, .keep_all = TRUE)

items_pos <- dat_distinct %>%
  select(all_of(mssb_items_dropped$mssb_pos))
cat("\n--- Pozitív reliabilitás ---\n")
alpha_pos <- psych::alpha(items_pos, check.keys = T)
item.alpha(items_pos)
print(alpha_pos)

```

``` {r worried_between_descriptive_visualization}

# Creating worried_mean
dat_1 <- dat_1 %>%
  group_by(id_esm) %>%
  mutate(worried = as.numeric(gsub(",", ".", as.character(worried)))) %>%
  mutate(worried_between = mean(worried, na.rm=T)) %>% 
  ungroup()

dat_distinct_worried <- dat_1 %>%
  distinct(id_esm, .keep_all = TRUE) %>%
  select(id_esm, day, beep, worried_between)

summary_worried_between <- dat_distinct_worried %>% 
  summarize(mean_worried_between = round(mean(worried_between, na.rm=T), digits = 2), 
            sd_worried_between = round(sd(worried_between, na.rm=T), digits = 2), 
            mdn_worried = round(median(worried_between, na.rm=T), digits = 2), 
            max_worried_between = round(max(worried_between, na.rm=T), digits = 2), 
            min_worried_between = round(min(worried_between, na.rm=T), digits = 2))

tibble(summary_worried_between)

worried_bw_vis <- ggplot(dat_distinct_worried, aes(worried_between)) +
  geom_histogram(bins = 40, fill = "#E5C494") +
  geom_vline(data = summary_worried_between, aes(xintercept = mdn_worried), linetype = "dotted", color = "#505354", size = 0.8)+ 
  geom_text(data = summary_worried_between, aes(x = mdn_worried, y = Inf, label = paste("Md =", sprintf("%.2f", mdn_worried))), vjust = 5, hjust = -0.1, fontface = "italic", size = 3.5) +
  labs(
    x = "Aggodalom átlagos szintje az ESM adatfelvétel során",
    y = "Résztvevők száma") +
  theme_minimal(base_size = 12) +
  theme(axis.title = element_text(size = 10))

print(worried_bw_vis)

```

``` {r worried_within_visualization}

# Visualizing within worried in ascending order
worried_wi_vis <- dat_1 %>%
  group_by(id_esm) %>%
  summarize(mean_worried = mean(worried, na.rm = T),
            sd_worried = sd(worried, na.rm = T)) %>%
  mutate(id_esm = fct_reorder(factor(id_esm), mean_worried)) %>%
  filter(!is.na(sd_worried)) %>%
  ungroup()

worried_wi_vis1 <- ggplot(worried_wi_vis, aes(id_esm, mean_worried)) +
  geom_pointrange(aes(ymin = mean_worried - sd_worried, ymax = mean_worried + sd_worried), color = "#E5C494", size = 0.2) +
  scale_x_discrete(breaks = function(x) x[seq(1, length(x), by = 10)]) +
  labs(
    x = "Résztvevők",
    y = "Aggodalom átlaga és szórása (SE)"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_blank()) 

print(worried_wi_vis1)

# Visualizing within worried in "normality shape"
worried_wi_vis_2 <- dat_1 %>%
  group_by(id_esm) %>%
  summarize(mean_worried = mean(worried, na.rm = T),
            sd_worried = sd(worried, na.rm = T)) %>%
  mutate(id_esm = fct_reorder(factor(id_esm), mean_worried)) %>%
  filter(!is.na(sd_worried)) %>%
  arrange(mean_worried)

n <- nrow(worried_wi_vis_2)
normality_arrange <- c(worried_wi_vis_2$id_esm[seq(1, n, by = 2)],
                       rev(worried_wi_vis_2$id_esm[seq(2, n, by = 2)]))

worried_wi_vis_2 <- worried_wi_vis_2 %>%
  mutate(id_esm = factor(id_esm, levels = normality_arrange))

worried_wi_vis2 <- ggplot(worried_wi_vis_2, aes(id_esm, mean_worried)) +
  geom_pointrange(aes(ymin = mean_worried - sd_worried, 
                      ymax = mean_worried + sd_worried), 
                  color = "#E5C494", size = 0.2) +
  scale_x_discrete(breaks = function(x) x[seq(1, length(x), by = 10)]) +
  labs(
    x = "Résztvevők",
    y = "Aggodalom átlaga és szórása (SE)"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_blank())

print(worried_wi_vis2)



```


